### ISSUE TITLE
add appveyor

### ISSUE THREAD

**Issue by kellyselden** [psbanka/eslint-plugin-hbs#14]
#10 is going to be doing newline splitting, so Windows tests are pretty necessary to prevent breaking.

**Comment by psbanka** [comment]
Haven't heard of this. Would this be done in addition to Travis to ensure builds pass properly on Windows?

**Comment by psbanka** [comment]
I've set up appveyor to some degree, but it's erroring out because there is no visual studio project or solution files...? https://ci.appveyor.com/project/psbanka/eslint-plugin-hbs 

I'm not likely to solve this, but if you have any solutions for this, @kellyselden – I'm happy to work with you to get CI functioning.

**Comment by kellyselden** [comment]
Now that you enabled it, I can add a config file.
